Update script

diff --git a/script/snap-xbps b/script/snap-xbps
--- a/script/snap-xbps
+++ b/script/snap-xbps
@@ -40,9 +40,20 @@ if [ -n "$PID_REMOVE" ]; then
 fi
 readonly pre_or_post=$1
 
+out() { printf "$1 $2\n" "${@:3}"; }
+
+error() { out ":: \033[00;31merror:\033[00m" "$@"; } >&2
+
+die() { 
+    [[ $ABORT_ON_FAIL == "no" ]] && exit 0
+    exit 1
+}
+
 read_config() {
     CONFIG_FILE="$1"
+echo "CONFIG_FILE--->$CONFIG_FILE"
     if [[ -f "$CONFIG_FILE" ]] && [[ -r "$CONFIG_FILE" ]]; then
+echo "CONFIG_FILE esiste!!"
         while IFS='= ' read lhs rhs; do
             if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
                 rhs="${rhs%%\#*}"
@@ -55,23 +66,11 @@ read_config() {
     fi
 }
 
-truncate_description() {
-    desc="$@"
-    if [[ "${#desc}" -gt $DESC_LIMIT ]]; then 
-        echo "$(echo $desc | cut -c 1-$DESC_LIMIT)..."
-    else
-        echo $desc
-    fi
+trapkill() { 
+    error "Exited due to user intervention."
+    die
 }
 
-out() { printf "$1 $2\n" "${@:3}"; }
-
-error() { out ":: \033[00;31merror:\033[00m" "$@"; } >&2
-
-die() { 
-    [[ $ABORT_ON_FAIL == "no" ]] && exit 0
-    exit 1
-}
 
 traperror() {
     error "Exited due to error on line $1"
@@ -82,11 +81,14 @@ traperror() {
     die
 }
 
-trapkill() { 
-    error "Exited due to user intervention."
-    die
+truncate_description() {
+    desc="$@"
+    if [[ "${#desc}" -gt $DESC_LIMIT ]]; then 
+        echo "$(echo $desc | cut -c 1-$DESC_LIMIT)..."
+    else
+        echo $desc
+    fi
 }
-
 
 trap 'traperror ${LINENO} $? "$BASH_COMMAND" $BASH_LINENO "${FUNCNAME[@]}"' ERR
 trap trapkill SIGTERM SIGINT
